#!/bin/bash

echo "=== Power Management Operations ==="
echo ""
echo "SAFE operations (won't shut down):"
echo ""
echo "Check shutdown status:"
echo "  systemctl is-system-running"
echo ""
echo "List shutdown jobs:"
echo "  systemctl list-jobs"
echo ""
echo "DANGEROUS operations (actually power off):"
echo ""
echo "Shutdown now:"
echo "  sudo systemctl poweroff"
echo ""
echo "Reboot now:"
echo "  sudo systemctl reboot"
echo ""
echo "Shutdown in 10 minutes with warning:"
echo "  sudo shutdown -h +10 'System maintenance'"
echo ""
echo "Cancel scheduled shutdown:"
echo "  sudo shutdown -c"
echo ""
echo "Suspend (sleep):"
echo "  sudo systemctl suspend"
echo ""
echo "Hibernate (if swap configured):"
echo "  sudo systemctl hibernate"
echo ""
echo "DO NOT RUN THESE COMMANDS on a system you're using!"
echo "Only run on test VMs or with intention."
