#!/bin/bash

echo "=== Systemd Target Management ==="
echo ""
echo "Current default target: $(systemctl get-default)"
echo ""

echo "Common Operations:"
echo ""
echo "1. Switch to multi-user (CLI only):"
echo "   sudo systemctl isolate multi-user.target"
echo ""
echo "2. Switch to graphical (GUI):"
echo "   sudo systemctl isolate graphical.target"
echo ""
echo "3. Set default to multi-user:"
echo "   sudo systemctl set-default multi-user.target"
echo ""
echo "4. Set default to graphical:"
echo "   sudo systemctl set-default graphical.target"
echo ""
echo "5. Boot into rescue mode (next boot):"
echo "   sudo systemctl reboot --rescue"
echo ""
echo "6. Boot into emergency mode (next boot):"
echo "   sudo systemctl reboot --emergency"
echo ""
echo "Note: Changing targets affects running system!"
echo "Use with caution on production systems."
