#!/bin/bash

echo "=== Cron Job Setup Guide ==="
echo ""
echo "Step 1: Create your script"
echo "  nano ~/my-script.sh"
echo ""
echo "Step 2: Make it executable"
echo "  chmod +x ~/my-script.sh"
echo ""
echo "Step 3: Test it manually"
echo "  ~/my-script.sh"
echo ""
echo "Step 4: Edit crontab"
echo "  crontab -e"
echo ""
echo "Step 5: Add line (example: every 5 minutes)"
echo "  */5 * * * * /home/$(whoami)/my-script.sh >> /tmp/script.log 2>&1"
echo ""
echo "Step 6: Save and exit"
echo ""
echo "Step 7: Verify it was added"
echo "  crontab -l"
echo ""
echo "Step 8: Check execution (wait 5 minutes)"
echo "  tail /tmp/script.log"
echo ""
echo "Current crontab:"
crontab -l 2>/dev/null || echo "  (No crontab installed)"
