#!/bin/bash

echo "=== Filesystem Check Practice ===" 
echo ""
echo "SAFE fsck Commands (for unmounted filesystems):"
echo ""
echo "1. Check if filesystem is clean:"
echo "   sudo fsck -n /dev/sdX1"
echo ""
echo "2. Check and auto-repair:"
echo "   sudo fsck -y /dev/sdX1"
echo ""
echo "3. Force check even if clean:"
echo "   sudo fsck -f /dev/sdX1"
echo ""
echo "4. Check with progress:"
echo "   sudo fsck -V /dev/sdX1"
echo ""
echo "NEVER run fsck on mounted filesystem!"
echo "Check if mounted: mount | grep sdX1"
echo "Unmount first: sudo umount /dev/sdX1"
echo ""
echo "Check filesystem type first:"
echo "  lsblk -f"
echo "  Use correct fsck type (fsck.ext4, fsck.xfs, etc.)"
